version: 2
updates:
  - package-ecosystem: github-actions
    labels: []
    directory: /
    target-branch: dev
    schedule:
      interval: weekly

  - package-ecosystem: npm
    labels: []
    directory: /
    target-branch: dev
    schedule:
      interval: weekly
    ignore:
      # version 10.x and later may not generate release notes correctly
      - dependency-name: "conventional-changelog-conventionalcommits"

  - package-ecosystem: gradle
    labels: []
    directory: /
    target-branch: dev
    schedule:
      interval: weekly
